name: clinico
description: Clinico App.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  firebase_core: ^1.20.0
  #firebase_analytics: ^9.3.0
  firebase_auth: ^3.6.2
  firebase_crashlytics: ^2.8.6
  cloud_firestore: ^3.4.3
  awesome_dialog: ^3.0.0
  firebase_messaging:
  firebase_storage: ^10.3.4
  url_launcher: ^6.1.2
  maps_launcher: ^2.0.1
  share: ^2.0.4
  flutter_material_pickers: ^3.1.2
  flutter_image_slideshow: ^0.1.2
  shared_preferences: ^2.0.13
  connectivity_plus: ^2.3.5
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5
  jiffy: ^5.0.0
  intl: ^0.17.0
  share_plus: ^4.0.7
  flutter_datetime_picker: ^1.5.1
  date_picker_timeline: ^1.2.3
  flutter_reorderable_list: ^1.1.0
  carousel_slider: ^4.0.0
  json_serializable: ^6.1.3
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.2
  loading_indicator: ^3.1.0
  email_validator: ^2.0.1
  phone_number: ^1.0.0
  google_maps_flutter: ^2.1.8
  google_maps_pick_place: ^0.8.7
  geolocator: ^8.2.1
  image: ^3.2.0
  #google_maps_webservice: ^0.0.20-nullsafety.5
  #tuple: ^2.0.0
  #google_maps_place_picker: ^2.1.0-nullsafety.3
  agora_rtc_engine: ^5.3.0
  permission_handler: ^9.2.0
  wakelock: ^0.6.2
  hexcolor:
  line_icons: ^2.0.1
  flutter_local_notifications: ^9.9.1
  cached_network_image: any
  bloc: any
  flutter_bloc: any
  http: any
  webview_flutter: any
  full_screen_image_null_safe: ^2.0.0
  photo_view: ^0.14.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/clinico_app_launcher.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Lateef
      fonts:
        - asset: fonts/Lateef-Regular.ttf

flutter_native_splash:

  color: "#f7f7f7"
  image: assets/icon/clinico_splash_screen.png
  android_12:
